workspace:
  base: /workspace
  path: app

when:
  - event: [push, tag]
    branch: main

steps:
  build-docker:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: git.eleith.com/eleith/miniflux-digest
      username: eleith
      dockerfile: Dockerfile
      registry: https://git.eleith.com
      auto_tag: true
      password:
        from_secret: gitea_docker_registry
  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
