workspace:
  base: /workspace
  path: app

when:
  - event: [push, tag]
    branch: main

steps:
  vendor:
    image: golang:1.24.5-alpine
    commands:
      - go mod vendor
  lint:
    image: golang:1.24.5-alpine
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run -v
  test:
    image: golang:1.24.5-alpine
    commands:
      - ./scripts/check-coverage.sh 60
  build-docker:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: git.eleith.com/eleith/miniflux-digest
      username: eleith
      dockerfile: Dockerfile
      registry: https://git.eleith.com
      auto_tag: true
      password:
        from_secret: gitea_docker_registry
  notify-success:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: success
      recipients_only: true
    when:
      - status: [success]
  notify-failure:
    image: deblan/woodpecker-email:3.2.0
    settings:
      dsn:
        from_secret: woodpecker_email_dsn
      from:
        address:
          from_secret: woodpecker_email_from_address
        name:
          from_secret: woodpecker_email_from_name
      recipients:
        from_secret: woodpecker_email_recipient
      level: failure
      recipients_only: true
    when:
      - status: [failure]
